version: "3.8"

services:
  backend:
    image: 319641750028.dkr.ecr.eu-north-1.amazonaws.com/algo_dev-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  compiler:
    image: 319641750028.dkr.ecr.eu-north-1.amazonaws.com/algo_dev-compiler:latest
    ports:
      - "8000:8000"
    env_file:
      - ./compiler/.env
    restart: always
