version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  compiler:
    build:
      context: ./compiler
    ports:
      - "8000:8000"
    env_file:
      - ./compiler/.env
    restart: always
